name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bazel
        uses: bazelbuild/setup-bazel@v6
        with:
          # Choose your Bazel version; 7.x works well with bzlmod
          bazel-version: 7.1.2
      - name: Build
        run: bazel build //...
      - name: Test
        run: bazel test //...
