name: Bazel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Bazel
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: 'latest'

    - name: Build
      run: bazel build //...

    - name: Test
      run: bazel test //...

